[tests] Integrate the testing infracture

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -13,6 +13,8 @@ top_srcdir := @top_srcdir@
 
 # Compiler programs & flags
 # !!! It assumes that ${top_srcdir} has been defined in the container file !!!
+AR := ar
+AR_FLAGS := rcsPT
 CC := @CC@
 CXX := @CXX@
 CPPFLAGS := @CPPFLAGS@ 
@@ -29,7 +31,8 @@ ALL_CXXFLAGS := ${ALL_CPPFLAGS} ${EXTRA_CXXFLAGS} ${CXXFLAGS}
 # Dependencies
 libcommon := third-party/libcommon/obj/libcommon.a
 libbacktrace := third-party/libcommon/lib/backtrace/lib/libbacktrace.a
-dependencies := ${libcommon} ${libbacktrace}
+archive := libgrapheval.a
+dependencies := ${archive} ${libcommon} ${libbacktrace}
 
 # Linker
 LIBS := @LIBS@ 
@@ -70,7 +73,7 @@ makedepend_cxx = @$(CXX) -MM $(ALL_CXXFLAGS) -MP -MT $@ -MF $(basename $@).d $<
 objectdirs := $(patsubst %./, %, $(sort $(addprefix ${objectdir}/, $(dir ${sources}))))
 objects_c := $(addprefix ${objectdir}/, $(patsubst %.c, %.o, $(filter %.c, ${sources})))
 objects_cxx := $(addprefix ${objectdir}/, $(patsubst %.cpp, %.o, $(filter %.cpp, ${sources})))
-objects := ${objects_c} ${objects_cxx}
+objects := $(patsubst %main.o,,${objects_c} ${objects_cxx})
 
 .DEFAULT_GOAL = all
 .PHONY: all
@@ -79,11 +82,13 @@ all: Makefile ${builddir}/${artifact}
 
 #############################################################################
 # Artifacts to build
-${builddir}/${artifact}: ${objects} ${dependencies} | ${builddir}
+${builddir}/${artifact}: ${objectdir}/main.o ${dependencies} | ${builddir}
 	${CXX} ${LDFLAGS} $^ -o $@
-	
+
 #############################################################################
 # Compiling the objects
+${archive}: ${objects}
+	$(AR) $(AR_FLAGS) $@ $?
 
 # Objects from C files
 ${objects_c} : ${objectdir}/%.o : %.c | ${objectdirs}
@@ -95,10 +100,57 @@ ${objects_cxx}: ${objectdir}/%.o : %.cpp | ${objectdirs}
 	${makedepend_cxx}
 	$(CXX) -c $(ALL_CXXFLAGS) $< -o $@
 
-# Create the build directories
-${builddir} ${objectdirs}:
+#############################################################################
+# Tests
+gtestdir := $(abspath ${builddir}/third-party/googletest)
+gtestlibs := $(addprefix ${gtestdir}/googlemock/gtest/,libgtest.a libgtest_main.a)
+testfolder := tests
+testsources := $(notdir $(wildcard ${srcdir}/${testfolder}/*.cpp))
+testbindir := $(abspath ${builddir}/${testfolder})
+testartifacts := $(addprefix tests/, $(basename ${testsources}))
+testignored := "" # space separated list
+
+.PHONY: check gtest_build
+check: ${testartifacts}
+	success=1; \
+	for f in `ls ${testbindir}`; do \
+		f="${testbindir}/$$f"; \
+		b=`basename $$f`; \
+		for igntest in "${testignored}"; do \
+			igntest="$$(echo -e "$${igntest}" | tr -d '[:space:]')"; \
+			if [ x"$$igntest" == x"$$b" ]; then \
+				echo "Test blacklisted and ignored: $$f"; \
+				continue 2; \
+			fi; \
+		done; \
+		echo "> Executing $$f ..."; \
+		if [ -x "$$f" ]; then \
+			$$f; \
+			if [ "$$?" -ne 0 ]; then \
+				echo "Test $$b failed. Avoiding running further tests."; \
+				success=0; \
+				break; \
+			fi; \
+		fi; \
+	done; \
+	if [ $$success -eq 1 ]; then \
+		echo "!!! All tests passed !!!"; \
+	fi;
+
+${testartifacts}: ${dependencies} | ${gtestlibs}
+${testartifacts}: % : %.cpp | ${testbindir}
+	${CXX} -I ${srcdir}/third-party/googletest/googletest/include ${LDFLAGS} $< -o $@ ${dependencies} ${gtestlibs}
+
+${gtestlibs}: ${gtestdir}
+${gtestdir}:
+	mkdir -pv ${gtestdir}
+	cmake -S ${srcdir}/third-party/googletest/ -B ${gtestdir}
+	make -C ${gtestdir} -j
+
+#############################################################################
+# Build directories
+${builddir} ${objectdirs} ${testbindir}:
 	mkdir -pv $@
-	
 	
 #############################################################################
 # libcommon
@@ -123,8 +175,11 @@ ${libbacktrace}: ${libcommon}
 .PHONY: clean
 clean:
 	rm -rf ${builddir}/${artifact}
+	rm -rf ${builddir}/${archive}
 	rm -rf ${builddir}/${objectdir}
 	rm -rf ${builddir}/third-party/libcommon
+	rm -rf ${gtestdir}
+	rm -rf ${testbindir}
 	
 #############################################################################
 # Regenerate the Makefile when the configuration has been changed
